apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    user: postgres
    database: sensors_db
    secureJsonData:
      password: postgres
    jsonData:
      database: sensors_db
      sslmode: 'disable'
      postgresVersion: 1500
    isDefault: true
    uid: dfi3wf0rciqrkf
