{
 "title": "Sistema EMS - Microgrid DC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"amp_bat\"\nFROM amp_bat\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"volt_bat\"\nFROM volt_bat\nWHERE $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"amp_pv\"\nFROM amp_panel\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS volt_pv\nFROM volt_panel\nWHERE $__timeFilter(timestamp)\nORDER BY timestamp DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"amp_load\"\nFROM amp_load\nWHERE $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"volt_load\"\nFROM volt_load\nWHERE $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"temp_pv\"\nFROM temp_panel \nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  value AS \"temp_bat\"\nFROM temp_bat\nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n    AVG(v.value * a.value) AS power_bat\nFROM volt_bat v\nJOIN amp_bat a\n    ON v.timestamp = a.timestamp\nWHERE $__timeFilter(v.timestamp);"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n    AVG(v.value * a.value) AS power_pv\nFROM volt_panel v\nJOIN amp_panel a\n    ON v.timestamp = a.timestamp\nWHERE $__timeFilter(v.timestamp);"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n    AVG(v.value * a.value) AS power_load\nFROM volt_load v\nJOIN amp_load a\n    ON v.timestamp = a.timestamp\nWHERE $__timeFilter(v.timestamp);"
    }
   ]
  },
  {
   "title": "Potencia del Panel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_V' AS metric\nFROM volt_panel\nORDER BY timestamp DESC\n"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_A' AS metric\nFROM amp_panel \nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "title": "Potencia de la Batería",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_V' AS metric\nFROM volt_bat \nORDER BY timestamp DESC\n"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_A' AS metric\nFROM amp_bat   \nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "title": "Potencia en la Carga",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_V' AS metric\nFROM volt_load  \nORDER BY timestamp DESC\n"
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT\n  timestamp AS time,\n  value,\n  'PV_A' AS metric\nFROM amp_load    \nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "title": "Panel",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje (V)\", \"timestamp\" FROM volt_panel   "
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Corriente (A)\", \"timestamp\" FROM amp_panel  "
    }
   ]
  },
  {
   "title": "Batería",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje (V)\", \"timestamp\" FROM volt_bat   "
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value  AS \"Corriente (A)\", \"timestamp\" FROM amp_bat    "
    }
   ]
  },
  {
   "title": "Carga",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje (V)\", \"timestamp\" FROM volt_load  "
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Corriente (A)\", \"timestamp\" FROM amp_load "
    }
   ]
  },
  {
   "title": "Temperatura de la batería",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value as \"Temperatura (°C)\", \"timestamp\" FROM temp_bat"
    }
   ]
  },
  {
   "title": "Temperatura del panel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value as \"Temperatura (°C)\", \"timestamp\" FROM temp_panel "
    }
   ]
  },
  {
   "title": "Batería Corriente",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Corriente (A)\", \"timestamp\" FROM amp_bat     "
    }
   ]
  },
  {
   "title": "Batería Voltaje",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje bat (V)\", \"timestamp\" FROM volt_bat        "
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje panel (V)\", \"timestamp\" FROM volt_panel       "
    },
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT value AS \"Voltaje load (V)\", \"timestamp\" FROM volt_load       "
    }
   ]
  }
 ]
}